#!/bin/bash

echo "-------------------------------------------"
echo "Script desenvolvido por Evert Ramos"
echo "Para atender ao trabalho do InfNet"
echo "Automação"
echo "DR1_TP3"
echo "-------------------------------------------"
echo "Automatizando o recon inicial"
echo "-------------------------------------------"

TARGET="${1:-127.0.0.1}"
PORTS="22 80 443 902 3306 8080 1716 52396"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
LOG_FULLFILE="scan_${TARGET}_${TIMESTAMP}.log"
# LOG_FULLFILE="scan_${TARGET}.log"

# função para receber o sinal (SIGINT) de interrupção do script (Ctrl+C)
trap_stop() {
  echo "Scan encerrado manualmente [Ctrl+C]"
  exit 130
}
trap trap_stop SIGINT

# Validar se as ferramentas necessárias estão instaladas
for tool in dig whois nmap; do
  if [[ -z "$(command -v "$tool")" ]]; then
      echo "Erro: A ferramenta '$tool' não está instalada. Por favor, instale-a para continuar."
      exit 1
  fi
done

# Identificação inicial do alvo
{
    echo "-------------------------------------------"
    echo "Data: $(date +"%d-%m-%Y %H:%M:%S")"
    echo "Alvo: $TARGET"
    if [[ "$TARGET" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        echo "Tipo: Endereço IP"
    else
        echo "Tipo: Domínio"
    fi
    echo "-------------------------------------------"

    echo "> dig"
    dig "${TARGET}"

    echo ""
    echo "-------------------------------------------"
    echo "> whois"
    whois "${TARGET}"

    echo ""
    echo "-------------------------------------------"
    echo "> nmap"
    sudo nmap -sn ${TARGET}
    # sudo nmap -sT --top-ports 100 ${TARGET}
    for PORT in ${PORTS}; do
      if [[ $(sudo nmap -p ${PORT} ${TARGET} | grep -c "open") -gt 0 ]]; then
        echo "Porta ${PORT} está aberta."
      else
        echo "Porta ${PORT} está fechada ou filtrada."
      fi
    done
    sudo nmap -O ${TARGET}

    echo ""
    echo "-------------------------------------------"
    echo ""
} > "$LOG_FULLFILE" 2>&1

echo "Scan concluído com sucesso!"
echo "-------------------------------------------"


exit 0
